In [21]:
import scipy.io as io
import numpy as np
import utils

In [22]:
def read_cmatrix(filename):
    return io.loadmat(filename + ".mat")[filename]

In [23]:
C_MATRIX = np.zeros((4,4))
for Set in [0,1,2,3,4]:
    filename = "Set%d_w_DNH_CRF"%Set
    C_MATRIX = C_MATRIX + read_cmatrix(filename)

In [24]:
mIOU, IOU, below_th = utils.compute_mIOU(C_MATRIX, th = 0.5)
OPA = utils.compute_OPA(C_MATRIX)
print('Confusion Matrix:\n', C_MATRIX)
print(' mIOU:', mIOU, '\n',
      'OPA:', OPA, '\n',
      'IOU for each class:', IOU, '\n',
      'Below_th:', below_th)

Confusion Matrix:
 [[  2.37638245e+08   5.33031500e+06   1.84275550e+07   3.09525800e+06]
 [  4.06756000e+06   4.27922220e+07   4.15434400e+06   3.28706000e+05]
 [  1.56159690e+07   2.50877900e+06   1.64555169e+08   3.66757000e+05]
 [  1.62185700e+06   6.35582000e+05   8.59311000e+05   3.59218590e+07]]
 mIOU: 0.795629623468 
 OPA: 0.894013891908 
 IOU for each class: [0.83149384139797056, 0.71537955074958992, 0.79692408974465545, 0.83872101197940752] 
 Below_th: False


## Save whole confusion matrix

In [25]:
filename = "WCM_w_DNH_CRF"
C_Matrix_dict = {filename:C_MATRIX}
filepath = filename + ".mat"
io.savemat(filepath, C_Matrix_dict)