In [1]:
import numpy as np

In [10]:
scales = 32
ratios = [0.5, 1, 2]
shape = [128, 128]
feature_stride = 4
anchor_stride = 1

In [3]:
scales, ratios = np.meshgrid(np.array(scales), np.array(ratios))
scales = scales.flatten()
ratios = ratios.flatten()

In [5]:
print(scales, ratios)

[32 32 32] [ 0.5  1.   2. ]


In [6]:
heights = scales / np.sqrt(ratios)
widths = scales * np.sqrt(ratios)

In [7]:
print(heights, widths)

[ 45.254834  32.        22.627417] [ 22.627417  32.        45.254834]


In [11]:
shifts_y = np.arange(0, shape[0], anchor_stride) * feature_stride
shifts_x = np.arange(0, shape[1], anchor_stride) * feature_stride
shifts_x, shifts_y = np.meshgrid(shifts_x, shifts_y)

In [13]:
print(shifts_x)

[[  0   4   8 ..., 500 504 508]
 [  0   4   8 ..., 500 504 508]
 [  0   4   8 ..., 500 504 508]
 ..., 
 [  0   4   8 ..., 500 504 508]
 [  0   4   8 ..., 500 504 508]
 [  0   4   8 ..., 500 504 508]]


In [14]:
box_widths, box_centers_x = np.meshgrid(widths, shifts_x)
box_heights, box_centers_y = np.meshgrid(heights, shifts_y)

In [17]:
print(box_centers_x)

[[  0   0   0]
 [  4   4   4]
 [  8   8   8]
 ..., 
 [500 500 500]
 [504 504 504]
 [508 508 508]]


In [18]:
box_centers = np.stack(
        [box_centers_y, box_centers_x], axis=2).reshape([-1, 2])
box_sizes = np.stack([box_heights, box_widths], axis=2).reshape([-1, 2])

In [21]:
print(box_centers.shape)
print(box_sizes.shape)

(49152, 2)
(49152, 2)


In [22]:
boxes = np.concatenate([box_centers - 0.5 * box_sizes,
                        box_centers + 0.5 * box_sizes], axis=1)

In [30]:
print(boxes.shape)
print(boxes[1,:])

(49152, 4)
[-16. -16.  16.  16.]
